// Mocks generated by Mockito 5.1.0 from annotations
// in search_address/test/bloc/address_bloc.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:search_address/src/models/address.dart' as _i3;

import 'address_bloc.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

class _FakeAddress_1 extends _i1.Fake implements _i3.Address {}

/// A class which mocks [MockAddressApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAddressApi extends _i1.Mock implements _i4.MockAddressApi {
  MockMockAddressApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  _i5.Future<_i3.Address> fetch(String? zipCode) =>
      (super.noSuchMethod(Invocation.method(#fetch, [zipCode]),
              returnValue: Future<_i3.Address>.value(_FakeAddress_1()))
          as _i5.Future<_i3.Address>);
}
